name: PR validation

on:
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Set up Tinygo
      uses: acifani/setup-tinygo@v2
      with:
        tinygo-version: '0.39.0'

    - name: Checks
      run: |
        go version
        tinygo version

    - name: Build
      run: tinygo build -o build.hex -target bluepill-clone -opt s -panic print -gc conservative -size full ./cmd/8x8_rgb_cube/main.go